name: Discord Notifications

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Notify on PR Opened to Main
        if: github.event.action == 'opened' && github.event.pull_request.base.ref == 'main'
        uses: Ilshidur/action-discord@master
        with:
          args: "📢 A new pull request has been opened targeting `main`: **${{ github.event.pull_request.title }}** by `${{ github.actor }}`. <${{ github.event.pull_request.html_url }}>"

      - name: Notify on PR Merged to Main
        if: github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        uses: Ilshidur/action-discord@master
        with:
          args: "✅ Pull request **${{ github.event.pull_request.title }}** has been merged into `main` by `${{ github.actor }}`. <${{ github.event.pull_request.html_url }}>"
